version: '3.8'
services:
  php: 
    build: './docker/php'
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - ${PHP_PORT:-8080}:80
    volumes:
      - ./:/var/www/html
    command: php -S 0.0.0.0:80 -t .

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mdp
      MYSQL_DATABASE: racoin
    ports:
      - "3306:3306"
  
  adminer:
    image: adminer
    ports:
      - "5555:8080"


